on: [push, pull_request]

env:
  CI: true

jobs:
  init:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: brad-jones/actions/cancel-redundant@v1.0.0
        with:
          token: ${{ secrets.CANCEL_GITHUB_TOKEN }}

  test:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/setup-go@v2, with: { go-version: "1.15.1" } }
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: go test -v ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - { uses: actions/setup-node@v1, with: { node-version: "12.x" } }
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - run: npx semantic-release
